# Generated by Django 4.0.5 on 2022-08-01 08:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_alter_student_course_alter_student_profile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='photo',
            field=models.ImageField(upload_to='course'),
        ),
    ]
