# Generated by Django 3.2.10 on 2022-08-01 15:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0010_alter_course_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='photo',
            field=models.ImageField(upload_to='course'),
        ),
    ]
