# Generated by Django 3.2.10 on 2022-08-02 16:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0013_document'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='meet',
            field=models.TextField(blank=True, null=True),
        ),
    ]
