# Generated by Django 4.0.5 on 2022-08-04 05:23

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0015_msg'),
    ]

    operations = [
        migrations.AddField(
            model_name='msg',
            name='data',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
