# Generated by Django 4.0.5 on 2022-08-04 05:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0016_msg_data'),
    ]

    operations = [
        migrations.RenameField(
            model_name='msg',
            old_name='data',
            new_name='date',
        ),
    ]
