# Generated by Django 4.0.5 on 2022-09-24 09:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0019_more_detail'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Detail',
        ),
        migrations.DeleteModel(
            name='More',
        ),
    ]
