# Generated by Django 4.0.5 on 2022-09-25 07:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0021_page_more_detail'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='more',
            name='page',
        ),
        migrations.DeleteModel(
            name='Detail',
        ),
        migrations.DeleteModel(
            name='More',
        ),
        migrations.DeleteModel(
            name='Page',
        ),
    ]
