# Generated by Django 4.0.5 on 2022-09-25 09:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0024_alter_lecture_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='detail',
            name='lecture',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='detail', to='main.lecture'),
        ),
    ]
