# Generated by Django 4.0.5 on 2022-09-25 14:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0026_resource'),
    ]

    operations = [
        migrations.AddField(
            model_name='resource',
            name='lecture',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='resource', to='main.lecture'),
            preserve_default=False,
        ),
    ]
