# Generated by Django 4.0.5 on 2022-09-26 02:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0030_lecturer'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Lecturer',
        ),
    ]
