# Generated by Django 4.0.5 on 2022-09-26 02:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0032_lecturer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lecturer',
            name='lecture',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Lecturer', to='main.lecture'),
        ),
    ]
