# Generated by Django 4.0.5 on 2022-09-26 02:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0033_alter_lecturer_lecture'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lecturer',
            name='lecture',
        ),
        migrations.AddField(
            model_name='lecture',
            name='lecturer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='main.lecturer'),
        ),
    ]
