# Generated by Django 4.0.5 on 2022-09-26 02:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0034_remove_lecturer_lecture_lecture_lecturer'),
    ]

    operations = [
        migrations.RenameField(
            model_name='lecture',
            old_name='lecturer',
            new_name='teacher',
        ),
    ]
