# Generated by Django 4.2.1 on 2023-05-09 12:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0039_rename_content1_lecture_introduce'),
    ]

    operations = [
        migrations.AddField(
            model_name='lecture',
            name='teacher_email',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='lecture',
            name='teacher_info',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='lecture',
            name='name',
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name='lecture',
            name='teacher',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
    ]
