# Generated by Django 4.2.1 on 2023-05-09 16:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0042_course_document_msg_profile_student_delete_user_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Msg',
        ),
    ]
