# Generated by Django 4.2.1 on 2023-05-12 07:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0043_delete_msg'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lecture',
            name='text',
        ),
    ]
