# Generated by Django 4.2.1 on 2023-05-13 06:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0046_delete_detail'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lecture',
            name='image',
            field=models.ImageField(default='lecture/course2.jpg', upload_to='lecture'),
        ),
    ]
