# Generated by Django 5.0.3 on 2024-05-06 13:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0047_alter_lecture_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='resource',
            name='file',
        ),
        migrations.AddField(
            model_name='resource',
            name='url',
            field=models.TextField(blank=True, null=True),
        ),
    ]
