# Generated by Django 5.0.3 on 2024-05-06 14:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0049_remove_document_upload_document_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='document',
            name='url',
            field=models.TextField(blank=True, null=True),
        ),
    ]
